#ifndef _GPIO_CFG_H_
#define _GPIO_CFG_H_

typedef enum {
  /*下面的序号和大小不能改变，和主板保持一致*/
  AM_IO_NULL=0,               
  AM_IO_MOTOR_L_PWM,
  AM_IO_MOTOR_R_PWM,
  AM_IO_LEFT_MOTOR_DIR, 
  AM_IO_RIGHT_MOTOR_DIR,
  AM_IO_MOTOR_DISABLE ,  	 
  AM_IO_MOTOR_WHEEL_RESET,   
  AM_IO_MOTOR_WHEEL_FAULT,    
  AM_IO_MOTOR_WHEEL_SLEEP,
  AM_IO_AUDIO_PWR_EN,
  AM_IO_CHARGER_ENABLE,
  AM_IO_BATTERY_I_CALIBRATE,
  AM_IO_WATCHDOG_CLEAR,
  AM_IO_VCC_KILL,
  AM_IO_SWITCHED_PWR_5V,
  AM_IO_SWITCHED_PWR_3V,
  AM_IO_FLASH_HOLD, 
  AM_IO_REV17,
  AM_IO_REV18,
  AM_IO_REV19, 
  HAL_MAX = 20,
}AM_IO_E;

#endif